# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170613_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_time',
            new_name='create_time',
        ),
    ]
