# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20170711_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
