# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20170711_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-first_commit']},
        ),
    ]
